browser = 'chrome'
email = 'soumyajitroy2411@gmail.com'
password = 'soumyajit2411#'
keywords = 'software engineer'
blacklistCompanies = ''
blackListTitles = ''
blackListjobLocations = ''
blackListLimitjobApplications = '67'
followCompanies = 'True'
alert = 'True'
workAuthorization = 'soumyajit2411#'
defaultInput = '1'
defaultCheck = 'Yes'
defaultRadio = 'Yes'
location = ['europe', 'northamerica']
experienceLevels = ['Internship', 'Entry_level']
datePosted = ['Past Month']
jobType = ['Part-time', 'Temporary', 'Intership']
remote = ['Remote']
salary = []
sort = ['Recent']
